# This action deploys a Python package to a Azure Function App .

name: Deploy Python Function App
description: Deploy a Python package to Azure Function App

inputs:
  python-version-file:
    required: true
    description: Path of the Python version file
  tenant-id:
    required: true
    description: Azure Tenant ID
  subscription-id:
    required: true
    description: Azure Subscription ID
  client-id:
    required: true
    description: Azure Client ID
  app-name:
    required: true
    description: Name of the Function App
  package-location:
    required: false
    description: Path of the package to publish
    default: '.'

runs:
  using: composite
  steps:
    - name: Login via Azure CLI
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
      with:
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        client-id: ${{ inputs.client-id }}

    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version-file: ${{ inputs.python-version-file }}
        cache: 'pip'
        architecture: 'x64'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.package-location }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Deploy function app
      uses: Azure/functions-action@fd80521afbba9a2a76a99ba1acc07aff8d733d11 # v1.5.2
      with:
        app-name: ${{ inputs.app-name }}
        package: ${{ inputs.package }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
