name: Terraform apply
description: "Terraform apply on Azure"

inputs:
  tenant-id:
    required: true
    description: Azure Tenant ID
  subscription-id:
    required: true
    description: Azure Subscription ID
  client-id:
    required: true
    description: Azure Client ID
  terraform-root:
    required: false
    description: Path of the folder where the root terraform module is found
    default: .
  terraform-plan-file:
    required: true
    description: Path of the Terraform plan to apply

runs:
  using: composite

  steps:
    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.terraform-root }}
      env:
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_USE_OIDC: "true"
        ARM_USE_AZUREAD: "true"
        PLAN_FILE: ${{ inputs.terraform-plan-file }}
      run: |
        terraform apply \
            -lock-timeout=3000s \
            -auto-approve \
            -input=false \
            "$PLAN_FILE"
