name: Terraform cache
description: "Cache Terraform modules and providers with commit scope"

inputs:
  terraform-env:
    required: true
    description: Terraform environment like in env/ folder
  terraform-root:
    required: false
    description: Path of the folder where the root terraform module is found
    default: .

runs:
  using: composite

  steps:
    - name: Terraform cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ inputs.terraform-root }}/.terraform
        key: terraform-${{ inputs.terraform-root }}-${{ inputs.terraform-env }}-${{ github.sha }}
        restore-keys: |
          terraform-${{ inputs.terraform-root }}-${{ inputs.terraform-env }}
