name: Terraform cache
description: "Cache Terraform modules and providers with commit scope"

inputs:
  terraform-env:
    required: true
    description: Terraform environment like in env/ folder
  terraform-root:
    required: false
    description: Path of the folder where the root terraform module is found
    default: .

runs:
  using: composite

  steps:
    - name: Terraform cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ inputs.terraform-root }}/.terraform
        key: terraform-${{ inputs.terraform-root }}-${{ inputs.terraform-env }}-${{ github.sha }}
        restore-keys: |
          terraform-${{ inputs.terraform-root }}-${{ inputs.terraform-env }}
