# This action deploys a container image to an Azure App Service
# performing a blue-green deployment with staging slot.  Login from
# GitHub to Azure is performed with managed identity and federated
# credential with OpenID Connect.

name: Deploy container App Service
description: Deploy a container image to Azure Linux App Service with container runtime

inputs:
  tenant-id:
    required: true
    description: Azure Tenant ID
  subscription-id:
    required: true
    description: Azure Subscription ID
  client-id:
    required: true
    description: Azure Client ID
  app-name:
    required: true
    description: Name of the Function App
  resource-group-name:
    required: true
    description: Name of the Resource Group of the Function App
  image:
    required: true
    description: Full name of the image to deploy, e.g. https://ghcr.io/myorg/myrepo:v0.1.0
  direct-deploy-to-prod:
    required: false
    description: If true, deploy directly to prod instead of blue-green with staging slot
    default: 'false'
  staging-slot-name:
    required: false
    description: Name of the staging slot
    default: staging
  staging-check-enabled:
    required: false
    description: Enable health check on staging slot before swapping
    default: 'false'
  staging-check-endpoint:
    required: false
    description: Endpoint to check on the staging slot
    default: /
  staging-check-match:
    required: false
    description: String to match in the response from the health check endpoint
    default: ''
  staging-check-retries:
    required: false
    description: Number of retries for the health check
    default: '5'
  staging-check-delay:
    required: false
    description: Delay between retries for the health check
    default: '10'

runs:
  using: composite
  steps:
    - name: Azure Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
      with:
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        client-id: ${{ inputs.client-id }}
  
    - name: Deploy
      uses: azure/webapps-deploy@de617f46172a906d0617bb0e50d81e9e3aec24c8 # v3.0.1
      if: inputs.direct-deploy-to-prod == 'true'
      with:
        resource-group-name: ${{ inputs.resource-group-name }}
        app-name: ${{ inputs.app-name }}
        images: ${{ inputs.image }}

    - name: Deploy to Staging Slot
      uses: azure/webapps-deploy@de617f46172a906d0617bb0e50d81e9e3aec24c8 # v3.0.1
      if: inputs.direct-deploy-to-prod != 'true'
      with:
        resource-group-name: ${{ inputs.resource-group-name }}
        app-name: ${{ inputs.app-name }}
        images: ${{ inputs.image }}
        slot-name: ${{ inputs.staging-slot-name }}
  
    - name: Run Health Check on Staging Slot
      if: inputs.staging-check-enabled == 'true'
      shell: bash
      env:
        APP_NAME: ${{ inputs.app-name }}
        SLOT_NAME: ${{ inputs.staging-slot-name }}
        ENDPOINT: ${{ inputs.staging-check-endpoint }}
        MATCH_STRING: ${{ inputs.staging-check-match }}
        RETRIES: ${{ inputs.staging-check-retries }}
        DELAY: ${{ inputs.staging-check-delay }}
      run: |
        echo "Health check enabled, running on staging slot..."

        # Get staging slot hostname
        URL="https://${APP_NAME}-${SLOT_NAME}.azurewebsites.net${ENDPOINT}"

        echo "Checking URL: $URL"

        for i in $(seq 1 "$RETRIES"); do
          echo "Attempt $i of $RETRIES..."

          # Perform curl and capture status code and body
          RESPONSE=$(curl -s -w "%{http_code}" "$URL")
          HTTP_STATUS=$(tail -n1 <<< "$RESPONSE")
          BODY=$(sed '$ d' <<< "$RESPONSE")

          echo "HTTP status: $HTTP_STATUS"

          # Check for 2xx status code
          if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
            # If a match string is provided, check for it in the body
            if [ -n "$MATCH_STRING" ]; then
              if [[ "$BODY" == *"$MATCH_STRING"* ]]; then
                echo "Health check passed. Found match string."
                exit 0
              else
                echo "Health check failed. Match string not found in response: $BODY"
              fi
            else
              echo "Health check passed."
              exit 0
            fi
          else
            echo "Health check failed with status: $HTTP_STATUS"
          fi

          if [ "$i" -lt "$RETRIES" ]; then
            echo "Waiting $DELAY seconds before next attempt..."
            sleep "$DELAY"
          fi
        done

        echo "::error::Health check failed after $RETRIES attempts."
        exit 1

    - name: Swap Staging and Production Slots
      shell: bash
      if: inputs.direct-deploy-to-prod != 'true'
      run: |
        az webapp deployment slot swap \
          -g ${{ inputs.resource-group-name }} \
          -n ${{ inputs.app-name }} \
          --slot ${{ inputs.staging-slot-name }} \
          --target-slot production
