name: Run Python script
description: "Run Python script with Pipenv managed dependencies"

inputs:
  context:
    required: false
    description: Path of the folder where the script is found
    default: '.'
  python-version-file:
    required: false
    description: Path of the python version file
    default: '.python-version'
  command:
    required: true
    description: Script to launch
  command-args:
    required: false
    description: Arguments of the script
    default: ''

runs:
  using: composite

  steps:
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version-file: '.python-version'
        cache: 'pipenv'
        architecture: 'x64'
  
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.context }}
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install --system --deploy --ignore-pipfile
  
    - name: Run Python script
      shell: bash
      run: |
        python ${{ inputs.context }}/${{ inputs.command }} ${{ inputs.args }}
