name: Run Python script
description: "Run Python script with Poetry managed dependencies"

inputs:
  context:
    required: false
    description: Path of the folder where the script is found
    default: '.'
  cwd:
    required: false
    description: Path of the folder where the script is executed
    default: '.'
  python-version-file:
    required: false
    description: Path of the python version file
    default: ''
  command:
    required: true
    description: Script to launch
  command-args:
    required: false
    description: Arguments of the script
    default: ''
  architecture:
    required: false
    description: Target architecture
    default: 'x64'

runs:
  using: composite

  steps:
    - name: Get Python version file
      shell: bash
      id: versfile
      env:
        PYTHON_VERSION_FILE: ${{ inputs.python-version-file }}
        CONTEXT: ${{ inputs.context }}
      run: |
        if [ -n "$PYTHON_VERSION_FILE" ]; then
          PY_VERS_FILE="$PYTHON_VERSION_FILE"
        else
          PY_VERS_FILE="$CONTEXT/.python-version"
        fi
        echo "py-vers-file=$PY_VERS_FILE" >> $GITHUB_OUTPUT

    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ${{ steps.versfile.outputs.py-vers-file }}
        cache: 'poetry'
        architecture: ${{ inputs.architecture }}
  
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.context }}
      run: poetry install
  
    - name: Run Python script
      shell: bash
      env:
        CWD: ${{ inputs.cwd }}
        CONTEXT: ${{ inputs.context }}
        COMMAND: ${{ inputs.command }}
      run: |
        cd $CWD
        poetry run -P $CONTEXT $COMMAND
