# This action performs a "semantic release" on GitHub releases, where
# the version and the changelog are calculated based on commit
# messages.  It also builds a Docker image and publishes it to the
# GitHub container registry.

name: Semantic release on GHCR
description: Semantic release publishing GitHub Release and Docker image in GitHub packages

inputs:
  context:
    required: false
    description: Docker context path
    default: '.'
  dockerfile:
    required: false
    description: Dockerfile path
    default: 'Dockerfile'
  image-suffix:
    required: false
    description: Suffix of the image name after repository name, e.g. ghcr.io/myorg/myrepo</this/is/the/suffix>. Include a starting / please!
    default: ''
  
outputs:
  new-release-published:
    description: Whether a new release was published or not
    value: ${{ steps.release.outputs.new_release_published }}
  new-release-version:
    description: Version of the new release published, if any
    value: ${{ steps.release.outputs.new_release_published }}
  new-release-image:
    description: Docker image published
    value: "ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:${{ steps.release.outputs.new_release_version }}"

runs:
  using: composite
  steps:
    - name: Release
      id: release
      uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
      with:
        semantic_version: 24.2.0
        extra_plugins: |
          @semantic-release/release-notes-generator@14.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      if: steps.release.outputs.new_release_published == 'true'

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      if: steps.release.outputs.new_release_published == 'true'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
      if: steps.release.outputs.new_release_published == 'true'
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:latest
          ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:${{ steps.release.outputs.new_release_version }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
