name: Quality Assurance

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  check-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
        with:
          tool_versions: |
            action-validator 0.6.0

      - name: Lint Actions
        shell: bash
        run: |
          action-validator --verbose **/action.yml
